version: "3.7"
services:
    rabbitmq:
      image: rabbitmq:3.8.2-management
      hostname: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
      volumes:
        - ./rabbitmq/data:/var/lib/rabbitmq
        - ./rabbitmq/log:/var/log/rabbitmq
    db:
      image: mariadb:10.4
      hostname: db
      ports:
          - "3307:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=app
        - MYSQL_USER=app
        - MYSQL_PASSWORD=secret
      volumes:
        - ./db/data:/var/lib/mysql
        - ./db/log:/var/log/mysql